---
title: "Asignacion_4_Derek_Arbaiza_Barrantes"
author: "Derek Arbaiza Barrantes"
date: '2022-09-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ff)
library(biglm)
library(ggplot2)
library(party)
library(tidyr)
library(lubridate)
library(forecast)

```


```{r}
RSS <- function(Pred, Real){
  ss <- sum((Real-Pred)^2)
  return (ss)
}

RSE <- function(Pred, Real, NumPred){
  N <- length(Real)-NumPred-1 
  ss <- sqrt((1/N)*RSS(Pred, Real))
  return(ss)
}

MSE <- function(Pred, Real){
  N <- length(Real)
  ss <- (1/N)*RSS(Pred, Real)
  return(ss)
}

relativeError <- function(Pred, Real){
  ss <- sum(abs(Real-Pred))/sum(abs(Real))
  return(ss)
}

RSE2 <- function(Pred, Real){
  N <- length(Real) - 2
  ss <- sqrt(sum((Real - Pred)^2))
  return((1/N) * ss)
}


```

```{r}
#Primera parte
ChurnTelecomTestData <- read.csv(file = "ChurnTelecomTest.csv", sep=",", dec=".", header = TRUE, row.names = 1)

ChurnTelecomTrainData <- read.csv(file = "ChurnTelecomTrain.csv", sep=",", dec=".", header = TRUE, row.names = 1)

ChurnTelecomTestData <- ChurnTelecomTestData[c(-26)]

ChurnTelecomTrainData <- ChurnTelecomTrainData[c(-26)]

ChurnTelecomTestData <- na.omit(ChurnTelecomTestData)

ChurnTelecomTrainData <- na.omit(ChurnTelecomTrainData)

#a)
myModel1 <- lm(MonthlyRevenue ~ ., data = ChurnTelecomTrainData)

myPrediction1 <- predict(myModel1, ChurnTelecomTestData)

#Suma de residuales
RSE(myPrediction1, ChurnTelecomTestData$MonthlyRevenue, 1)

#Error cuadratico medio
MSE(myPrediction1, ChurnTelecomTestData$MonthlyRevenue)

#Error relativo
relativeError(myPrediction1, ChurnTelecomTestData$MonthlyRevenue)


newDataChurnTrain <- read.csv.ffdf(file = "ChurnTelecomTest.csv", sep=",", dec=".", header = T)

myModel2 <- biglm(MonthlyRevenue ~ OverageMinutes, data = newDataChurnTrain)

myDataFrame2 <- data.frame(OverageMinutes = c(250, 6, 97),
                           MonthlyRevenue = c(2.23, 0.25, 0.5))
myPrediction2 <- predict(myModel2, myDataFrame2, interval = "confidence")

#b)
myModel3 <- lm(MonthlyRevenue ~ OverageMinutes + TotalRecurringCharge + ReceivedCalls, data = ChurnTelecomTestData)

myPrediction3 <- predict(myModel3, ChurnTelecomTestData, interval = "confidence")

#Suma de residuales
RSE(myPrediction3, ChurnTelecomTestData$MonthlyRevenue, 3)

#Error cuadratico medio
MSE(myPrediction3, ChurnTelecomTestData$MonthlyRevenue)

#Error relativo
relativeError(myPrediction3, ChurnTelecomTestData$MonthlyRevenue)


myModel4 <- biglm(MonthlyRevenue ~ OverageMinutes + TotalRecurringCharge + ReceivedCalls, data = newDataChurnTrain)

myDataFrame4 <- data.frame(OverageMinutes = c(250, 6, 97),
                           MonthlyRevenue = c(2.23, 0.25, 0.5),
                           TotalRecurringCharge = c(85,37,75),
                           ReceivedCalls = c(97.2, 51.7, 288))
myPrediction4 <- predict(myModel4, myDataFrame4, interval = "confidence")

#myError <- RSE2(as.ff(myPrediction4[,1]), myDataFrame4$OverageMinutes)

```

```{r}
#Parte 2

ChurnTelecomTrainData$Churn <- factor(ChurnTelecomTrainData$Churn)
ChurnTelecomTrainData$MadeCallToRetentionTeam <- factor(ChurnTelecomTrainData$MadeCallToRetentionTeam)
ChurnTelecomTrainData$Occupation <- factor(ChurnTelecomTrainData$Occupation)
ChurnTelecomTrainData$MaritalStatus <- factor(ChurnTelecomTrainData$MaritalStatus)

ChurnTelecomTestData$Churn <- factor(ChurnTelecomTestData$Churn)
ChurnTelecomTestData$MadeCallToRetentionTeam <- factor(ChurnTelecomTestData$MadeCallToRetentionTeam)
ChurnTelecomTestData$Occupation <- factor(ChurnTelecomTestData$Occupation)
ChurnTelecomTestData$MaritalStatus <- factor(ChurnTelecomTestData$MaritalStatus)


#a)
myModel5 <- ctree(Churn ~ IncomeGroup + MonthlyMinutes + ReceivedCalls + MonthsInService  + 
MadeCallToRetentionTeam + Occupation + MaritalStatus, data = ChurnTelecomTrainData)

#b)
plot(myModel5)

#c)
myPrediction5 <- predict(myModel5, ChurnTelecomTestData)

#d)
confusionMatrix <- table(ChurnTelecomTestData$Churn, myPrediction5)
success <- sum(diag(confusionMatrix))/sum(confusionMatrix)

error <- 1- success

cat("Da un error de 27% lo que considero que es bajo para un modelo predictorio."
)

cat("Considero que sí hay mejores variables predictorias, evitaría las de naturaleza cualitativa y me enfocaría en cuantitativas."
)
```

```{r}
#Parte 3
CovidActives <- read.csv(file = "ACTIVOS.csv", sep=";", header=TRUE, encoding = "UTF-8")
CovidDeads <- read.csv(file = "FALLECIDOS.csv", sep=";", header=TRUE, encoding = "UTF-8")
CovidPositives <- read.csv(file = "POSITIVOS.csv", sep=";", header=TRUE, encoding = "UTF-8")
CovidPositives <- CovidPositives[c(-5,-6,-7,-8,-9,-10,
                                   -11,-12,-13,-14,-15,-16,-17,-18,-19,-20,
                                   -21,-22,-23,-24,-25,-26,-27,-28,-29,-30,
                                   -31,-32,-33,-34,-35,-36,-37,-38,-39,-40,
                                   -41)]
CovidRecovered <- read.csv(file = "RECUPERADOS.csv", sep=";", header=TRUE, encoding = "UTF-8")
CovidRecovered <- CovidRecovered[c(-5,-6,-7,-8)]

Datos.activos.ordenados <- gather(data = CovidActives, key = "Fecha", value = "valores", 5:396)
Datos.activos.ordenados$Tipo <- "Activo"
Datos.activos.ordenados$Fecha <- gsub("X", "", as.character(Datos.activos.ordenados$Fecha))
Datos.activos.ordenados$Fecha <- dmy(Datos.activos.ordenados$Fecha)

Datos.muertos.ordenados <- gather(data = CovidDeads, key = "Fecha", value = "valores", 5:396)
Datos.muertos.ordenados$Tipo <- "Muerto"
Datos.muertos.ordenados$Fecha <- gsub("X", "", as.character(Datos.muertos.ordenados$Fecha))
Datos.muertos.ordenados$Fecha <- dmy(Datos.muertos.ordenados$Fecha)

Datos.positivos.ordenados <- gather(data = CovidPositives, key = "Fecha", value = "valores",  5:396)
Datos.positivos.ordenados$Tipo <- "Positivo"
Datos.positivos.ordenados$Fecha <- gsub("X", "", as.character(Datos.positivos.ordenados$Fecha))
Datos.positivos.ordenados$Fecha <- dmy(Datos.positivos.ordenados$Fecha)

Datos.recuperados.ordenados <- gather(data = CovidRecovered, key = "Fecha", value = "valores",  5:396)
Datos.recuperados.ordenados$Tipo <- "Recuperado"
Datos.recuperados.ordenados$Fecha <- gsub("X", "", as.character(Datos.recuperados.ordenados$Fecha))
Datos.recuperados.ordenados$Fecha <- dmy(Datos.recuperados.ordenados$Fecha)

Datos.finales <- rbind(Datos.activos.ordenados, Datos.muertos.ordenados, Datos.positivos.ordenados, Datos.recuperados.ordenados)

#a

Plot1 <- subset(Datos.activos.ordenados, cod_provin == 1)
Plot11 <- aggregate(Datos.activos.ordenados$valores, by=list(Datos.activos.ordenados$Fecha), sum)

plot(Plot11, main = "Evolución de casos en la provincia de San José", xlab="Año", ylab="Cantidad de casos", type="line", col="red")

Plot2 <- subset(Datos.muertos.ordenados, cod_provin == 7)
Plot22 <- aggregate(Plot2$valores, by=list(Plot2$canton), sum)
Plot22t <- table(Plot22$Group.1, Plot22$x)

barplot(Plot22t, main = "cantidad de casos por cantón de la provincia de Limón")

Plot3po <- subset(Datos.positivos.ordenados, cod_provin == 5)
Plot3re <- subset(Datos.recuperados.ordenados ,cod_provin == 5)
Plot33po <- aggregate(Plot3po$valores, by=list(Plot3po$Fecha), sum)
Plot33re <- aggregate(Plot3re$valores, by=list(Plot3re$Fecha), sum)

plot(Plot33po, type = "o", col="blue", main="Casos positivos vs Casos recuperados en la provincia de Guanacaste") +
lines(Plot33re, type="o", pch=22, lty=2, col="red")


#c
dim(Datos.finales)
Datos.finales.tiempo <- ts(Datos.finales[,5], freq = 12)

myModel6 <- auto.arima(Datos.finales.tiempo)

mypredicition6 <- predict(myModel6)

#d

Datos.finales <- na.omit(Datos.finales)
Datos.finales.regresion <- Datos.finales[c(1,3,6)]

corelation <- cor(Datos.finales.regresion)

myModel7 <- lm(valores ~ cod_provin + cod_canton, data = Datos.finales) 

myPrediction7 <- predict(myModel7, Datos.finales, interval = "confidence")


#Muchas gracias profe por el conocimiento durante todos los cursos y paciencia para resolver mis dudas.
#You rock profe! :)

```

